# Generated by Django 5.2.6 on 2025-09-22 03:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaseTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visibility_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("REGISTERED", "Registered Users"),
                            ("AGENCY_ONLY", "Agency Only"),
                            ("LANDLORD_ONLY", "Landlord Only"),
                            ("TENANT_ONLY", "Tenant Only"),
                            ("CLASSIFIED", "Classified"),
                            ("SYSTEM", "System Only"),
                        ],
                        db_index=True,
                        default="REGISTERED",
                        help_text="Visibility level for this record",
                        max_length=20,
                    ),
                ),
                (
                    "visibility_groups",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON array of group names with access (e.g., ['landlords', 'agents'])",
                    ),
                ),
                (
                    "visibility_users",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON array of specific user IDs with access",
                    ),
                ),
                (
                    "visibility_exceptions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Complex visibility rules as JSON (e.g., {'tenant': 'LEASE.active'})",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this record has been soft deleted",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="When this record was deleted", null=True
                    ),
                ),
                (
                    "retention_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this record will be permanently deleted",
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for identification", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description and usage notes"
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("retail", "Retail"),
                            ("office", "Office"),
                        ],
                        default="residential",
                        help_text="Type of lease template",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this template is available to all users",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a default template for the type",
                    ),
                ),
                (
                    "default_lease_duration_months",
                    models.PositiveIntegerField(
                        default=12, help_text="Default lease duration in months"
                    ),
                ),
                (
                    "default_notice_period_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Default notice period in days"
                    ),
                ),
                (
                    "default_security_deposit_months",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("1.0"),
                        help_text="Default security deposit in months of rent",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0")),
                            django.core.validators.MaxValueValidator(Decimal("12.0")),
                        ],
                    ),
                ),
                (
                    "terms_and_conditions",
                    models.TextField(help_text="Standard terms and conditions text"),
                ),
                (
                    "special_clauses",
                    models.TextField(
                        blank=True, help_text="Special clauses or additional terms"
                    ),
                ),
                (
                    "default_max_occupants",
                    models.PositiveIntegerField(
                        default=2, help_text="Default maximum number of occupants"
                    ),
                ),
                (
                    "default_pets_allowed",
                    models.BooleanField(default=False, help_text="Default pets policy"),
                ),
                (
                    "default_smoking_allowed",
                    models.BooleanField(
                        default=False, help_text="Default smoking policy"
                    ),
                ),
                (
                    "default_subletting_allowed",
                    models.BooleanField(
                        default=False, help_text="Default subletting policy"
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this template has been used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this template",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_lease_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who deleted this record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lease Template",
                "verbose_name_plural": "Lease Templates",
                "db_table": "lease_templates",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["template_type"], name="lease_templ_templat_3bc32b_idx"
                    ),
                    models.Index(
                        fields=["is_public"], name="lease_templ_is_publ_e46e8f_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="lease_templ_is_defa_559cb2_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="lease_templ_created_6ca3b3_idx"
                    ),
                    models.Index(fields=["name"], name="lease_templ_name_e2ef54_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("template_type", "is_default", "created_by"),
                        name="unique_default_template_per_type_per_user",
                    )
                ],
            },
        ),
    ]
