# Generated by Django 5.2.6 on 2025-09-03 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Conversation title (optional for direct messages)",
                        max_length=200,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Message"),
                            ("property_inquiry", "Property Inquiry"),
                            ("group", "Group Chat"),
                        ],
                        default="direct",
                        help_text="Type of conversation",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the conversation is active"
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Whether the conversation is archived"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of the last message", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "db_table": "conversations",
                "ordering": ["-last_message_at", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("admin", "Admin"),
                            ("owner", "Owner"),
                        ],
                        default="member",
                        help_text="Role of the participant in the conversation",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the participant is active in the conversation",
                    ),
                ),
                (
                    "is_muted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the participant has muted notifications",
                    ),
                ),
                (
                    "last_read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the participant last read messages",
                        null=True,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "left_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the participant left the conversation",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation Participant",
                "verbose_name_plural": "Conversation Participants",
                "db_table": "conversation_participants",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        help_text="Type of message",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Message content")),
                (
                    "file_attachment",
                    models.FileField(
                        blank=True,
                        help_text="File attachment (for file/image messages)",
                        null=True,
                        upload_to="messages/",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, help_text="Original filename", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "is_edited",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been edited"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Whether the message has been deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "edited_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the message was last edited",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "db_table": "messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message Read Status",
                "verbose_name_plural": "Message Read Statuses",
                "db_table": "message_read_statuses",
            },
        ),
    ]
