# Generated by Django 5.2.6 on 2025-09-03 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("messaging", "0001_initial"),
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="property",
            field=models.ForeignKey(
                blank=True,
                help_text="Related property (for property inquiries)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="properties.property",
            ),
        ),
        migrations.AddField(
            model_name="conversationparticipant",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="messaging.conversation",
            ),
        ),
    ]
