name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Jaston Real Estate
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out this form as completely as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported already
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: I am using the latest version of Jaston Real Estate
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by this bug?
      options:
        - Frontend (React/TypeScript)
        - Backend (Django/Python)
        - Database (PostgreSQL)
        - Authentication/Authorization
        - Property Management
        - Lease Management
        - Maintenance System
        - Messaging/Notifications
        - Payment/Wallet System
        - API/Integration
        - Documentation
        - DevOps/Infrastructure
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable, data loss, security vulnerability)
        - High (Major functionality broken, significant impact)
        - Medium (Feature partially broken, workaround available)
        - Low (Minor issue, cosmetic problem)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images/videos here or paste URLs

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - OS: [e.g., Ubuntu 22.04, Windows 11, macOS 13]
        - Browser: [e.g., Chrome 120, Firefox 121, Safari 17]
        - Node.js version: [e.g., 18.19.0]
        - Python version: [e.g., 3.13.0]
        - Django version: [e.g., 5.2.6]
        - Database: [e.g., PostgreSQL 17.0]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please include any relevant error logs, stack traces, or console output
      placeholder: Paste error logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Assessment
      description: Please check all that apply
      options:
        - label: This bug affects user authentication/login
        - label: This bug affects property management functionality
        - label: This bug affects lease management
        - label: This bug affects payment processing
        - label: This bug affects data integrity
        - label: This bug affects system performance
        - label: This bug affects security
        - label: This bug affects mobile users
        - label: This bug affects accessibility

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: What type of user are you?
      options:
        - Property Manager
        - Landlord
        - Tenant
        - System Administrator
        - Developer
        - Other
    validations:
      required: true