# Generated by Django 5.2.6 on 2025-09-04 19:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("html_content", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("target_categories", models.JSONField(blank=True, default=list)),
                (
                    "target_frequency",
                    models.CharField(
                        choices=[
                            ("all", "All Subscribers"),
                            ("daily", "Daily Subscribers"),
                            ("weekly", "Weekly Subscribers"),
                            ("monthly", "Monthly Subscribers"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("total_sent", models.PositiveIntegerField(default=0)),
                ("total_delivered", models.PositiveIntegerField(default=0)),
                ("total_opened", models.PositiveIntegerField(default=0)),
                ("total_clicked", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "newsletter_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_token",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("is_confirmed", models.BooleanField(default=False)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "newsletter_subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="newsletter.newslettercampaign",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="newsletter.newslettersubscription",
                    ),
                ),
            ],
            options={
                "db_table": "newsletter_deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="newslettercampaign",
            index=models.Index(fields=["status"], name="newsletter__status_4e6eb2_idx"),
        ),
        migrations.AddIndex(
            model_name="newslettercampaign",
            index=models.Index(
                fields=["scheduled_at"], name="newsletter__schedul_2f2dd9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettercampaign",
            index=models.Index(
                fields=["created_by"], name="newsletter__created_550fd5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscription",
            index=models.Index(fields=["email"], name="newsletter__email_71b1f8_idx"),
        ),
        migrations.AddIndex(
            model_name="newslettersubscription",
            index=models.Index(
                fields=["is_active"], name="newsletter__is_acti_9643c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newslettersubscription",
            index=models.Index(
                fields=["is_confirmed"], name="newsletter__is_conf_f27152_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletterdelivery",
            index=models.Index(fields=["status"], name="newsletter__status_f44768_idx"),
        ),
        migrations.AddIndex(
            model_name="newsletterdelivery",
            index=models.Index(
                fields=["campaign"], name="newsletter__campaig_1dc840_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsletterdelivery",
            index=models.Index(
                fields=["subscription"], name="newsletter__subscri_d230a1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="newsletterdelivery",
            unique_together={("campaign", "subscription")},
        ),
    ]
